# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelLampNumber = QtWidgets.QLabel(self.frame_2)
        self.labelLampNumber.setObjectName("labelLampNumber")
        self.verticalLayout_2.addWidget(self.labelLampNumber)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.textLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.textLog.setObjectName("textLog")
        self.verticalLayout_4.addWidget(self.textLog)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.labelLampUnderTest = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLampUnderTest.sizePolicy().hasHeightForWidth())
        self.labelLampUnderTest.setSizePolicy(sizePolicy)
        self.labelLampUnderTest.setMinimumSize(QtCore.QSize(200, 100))
        self.labelLampUnderTest.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelLampUnderTest.setFrameShape(QtWidgets.QFrame.Box)
        self.labelLampUnderTest.setObjectName("labelLampUnderTest")
        self.verticalLayout_5.addWidget(self.labelLampUnderTest)
        self.widgetLamps = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetLamps.sizePolicy().hasHeightForWidth())
        self.widgetLamps.setSizePolicy(sizePolicy)
        self.widgetLamps.setMinimumSize(QtCore.QSize(200, 0))
        self.widgetLamps.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widgetLamps.setWidgetResizable(True)
        self.widgetLamps.setObjectName("widgetLamps")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 198, 321))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(4, 4, 4, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetLamps.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.widgetLamps)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinCounterPass = QtWidgets.QSpinBox(self.widget)
        self.spinCounterPass.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinCounterPass.setObjectName("spinCounterPass")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinCounterPass)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinCounterFail = QtWidgets.QSpinBox(self.widget)
        self.spinCounterFail.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinCounterFail.setObjectName("spinCounterFail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinCounterFail)
        self.horizontalLayout_2.addWidget(self.widget)
        self.btnResetCounters = QtWidgets.QPushButton(self.frame_3)
        self.btnResetCounters.setObjectName("btnResetCounters")
        self.horizontalLayout_2.addWidget(self.btnResetCounters)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.frame_3)
        self.labelHueLogo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHueLogo.sizePolicy().hasHeightForWidth())
        self.labelHueLogo.setSizePolicy(sizePolicy)
        self.labelHueLogo.setMinimumSize(QtCore.QSize(200, 100))
        self.labelHueLogo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelHueLogo.setFrameShape(QtWidgets.QFrame.Box)
        self.labelHueLogo.setObjectName("labelHueLogo")
        self.horizontalLayout.addWidget(self.labelHueLogo)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Refurbish Tester v2.0"))
        self.labelLampNumber.setText(_translate("MainWindow", "LAMP 10NC"))
        self.label_4.setText(_translate("MainWindow", "STATUS: PASS / FAIL"))
        self.labelLampUnderTest.setText(_translate("MainWindow", "LAMP UNDER TEST"))
        self.label_12.setText(_translate("MainWindow", "pass"))
        self.label_13.setText(_translate("MainWindow", "fail"))
        self.btnResetCounters.setText(_translate("MainWindow", "reset"))
        self.labelHueLogo.setText(_translate("MainWindow", "PHILIPS HUE LOGO"))

