# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow_v2b.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelProductTest = QtWidgets.QLabel(self.frame_2)
        self.labelProductTest.setObjectName("labelProductTest")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelProductTest)
        self.labelLampNumber = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelLampNumber.setFont(font)
        self.labelLampNumber.setObjectName("labelLampNumber")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelLampNumber)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineBarcode = QtWidgets.QLineEdit(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineBarcode.setFont(font)
        self.lineBarcode.setObjectName("lineBarcode")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineBarcode)
        self.labelDescription = QtWidgets.QLabel(self.frame_2)
        self.labelDescription.setObjectName("labelDescription")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelDescription)
        self.labelLampDescription = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelLampDescription.setFont(font)
        self.labelLampDescription.setObjectName("labelLampDescription")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelLampDescription)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.textLog = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(12)
        self.textLog.setFont(font)
        self.textLog.setObjectName("textLog")
        self.verticalLayout_2.addWidget(self.textLog)
        self.frameMessage = QtWidgets.QFrame(self.centralwidget)
        self.frameMessage.setMinimumSize(QtCore.QSize(0, 0))
        self.frameMessage.setFrameShape(QtWidgets.QFrame.Box)
        self.frameMessage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMessage.setObjectName("frameMessage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameMessage)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labelMessage = QtWidgets.QLabel(self.frameMessage)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelMessage.setFont(font)
        self.labelMessage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelMessage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_6.addWidget(self.labelMessage)
        self.verticalLayout_2.addWidget(self.frameMessage)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelPassFail = QtWidgets.QLabel(self.frame)
        self.labelPassFail.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelPassFail.setFont(font)
        self.labelPassFail.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelPassFail.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPassFail.setObjectName("labelPassFail")
        self.verticalLayout_3.addWidget(self.labelPassFail)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinCounterPass = QtWidgets.QSpinBox(self.widget)
        self.spinCounterPass.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinCounterPass.setMaximum(1000000)
        self.spinCounterPass.setObjectName("spinCounterPass")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinCounterPass)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.spinCounterFail = QtWidgets.QSpinBox(self.widget)
        self.spinCounterFail.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinCounterFail.setMaximum(1000000)
        self.spinCounterFail.setObjectName("spinCounterFail")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinCounterFail)
        self.horizontalLayout_2.addWidget(self.widget)
        self.btnResetCounters = QtWidgets.QPushButton(self.frame_3)
        self.btnResetCounters.setObjectName("btnResetCounters")
        self.horizontalLayout_2.addWidget(self.btnResetCounters)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLampUnderTest = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLampUnderTest.sizePolicy().hasHeightForWidth())
        self.labelLampUnderTest.setSizePolicy(sizePolicy)
        self.labelLampUnderTest.setMinimumSize(QtCore.QSize(200, 200))
        self.labelLampUnderTest.setMaximumSize(QtCore.QSize(320, 16777215))
        self.labelLampUnderTest.setFrameShape(QtWidgets.QFrame.Box)
        self.labelLampUnderTest.setObjectName("labelLampUnderTest")
        self.verticalLayout.addWidget(self.labelLampUnderTest)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.labelSettingsFilename = QtWidgets.QLabel(self.groupBox)
        self.labelSettingsFilename.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.labelSettingsFilename.setFont(font)
        self.labelSettingsFilename.setObjectName("labelSettingsFilename")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelSettingsFilename)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.labelSettingsVersion = QtWidgets.QLabel(self.groupBox)
        self.labelSettingsVersion.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.labelSettingsVersion.setFont(font)
        self.labelSettingsVersion.setObjectName("labelSettingsVersion")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelSettingsVersion)
        self.verticalLayout.addWidget(self.groupBox)
        self.listLampTests = QtWidgets.QListWidget(self.centralwidget)
        self.listLampTests.setMaximumSize(QtCore.QSize(320, 16777215))
        self.listLampTests.setObjectName("listLampTests")
        self.verticalLayout.addWidget(self.listLampTests)
        self.labelHueLogo = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelHueLogo.sizePolicy().hasHeightForWidth())
        self.labelHueLogo.setSizePolicy(sizePolicy)
        self.labelHueLogo.setMinimumSize(QtCore.QSize(320, 100))
        self.labelHueLogo.setMaximumSize(QtCore.QSize(320, 16777215))
        self.labelHueLogo.setFrameShape(QtWidgets.QFrame.Box)
        self.labelHueLogo.setObjectName("labelHueLogo")
        self.verticalLayout.addWidget(self.labelHueLogo)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Refurbish Tester v2.0"))
        self.labelProductTest.setText(_translate("MainWindow", "Product Test:"))
        self.labelLampNumber.setText(_translate("MainWindow", "-"))
        self.label_4.setText(_translate("MainWindow", "QR code:"))
        self.labelDescription.setText(_translate("MainWindow", "Description:"))
        self.labelLampDescription.setText(_translate("MainWindow", "-"))
        self.labelMessage.setText(_translate("MainWindow", "TextLabel"))
        self.labelPassFail.setText(_translate("MainWindow", "STATUS: PASS / FAIL"))
        self.label_12.setText(_translate("MainWindow", "pass"))
        self.label_13.setText(_translate("MainWindow", "fail"))
        self.btnResetCounters.setText(_translate("MainWindow", "reset"))
        self.labelLampUnderTest.setText(_translate("MainWindow", "LAMP UNDER TEST"))
        self.groupBox.setTitle(_translate("MainWindow", "Lamp settings"))
        self.label.setText(_translate("MainWindow", "filename:"))
        self.labelSettingsFilename.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "version:"))
        self.labelSettingsVersion.setText(_translate("MainWindow", "-"))
        self.labelHueLogo.setText(_translate("MainWindow", "PHILIPS HUE LOGO"))

